// <auto-generated />
using System;
using BMS_POS_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BMS_POS_API.Migrations
{
    [DbContext(typeof(BmsPosDbContext))]
    [Migration("20250903002611_FixProductCategoriesNaming")]
    partial class FixProductCategoriesNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BMS_POS_API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("pin");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.InventoryCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompletedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("completed_by_employee_id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<string>("CountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("count_name");

                    b.Property<string>("CountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("count_type");

                    b.Property<decimal>("NetVarianceValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("net_variance_value");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("StartedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("started_by_employee_id");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalDiscrepancies")
                        .HasColumnType("integer")
                        .HasColumnName("total_discrepancies");

                    b.Property<int>("TotalItemsCounted")
                        .HasColumnType("integer")
                        .HasColumnName("total_items_counted");

                    b.Property<decimal>("TotalOverageValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_overage_value");

                    b.Property<decimal>("TotalShrinkageValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_shrinkage_value");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByEmployeeId");

                    b.HasIndex("StartedByEmployeeId");

                    b.ToTable("inventory_counts", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.InventoryCountItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost_per_unit");

                    b.Property<int>("CountedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("counted_by_employee_id");

                    b.Property<DateTime>("CountedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("counted_date");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("counted_quantity");

                    b.Property<string>("DiscrepancyReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("discrepancy_reason");

                    b.Property<int>("InventoryCountId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_count_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int?>("ProductBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("product_batch_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("system_quantity");

                    b.Property<int>("Variance")
                        .HasColumnType("integer")
                        .HasColumnName("variance");

                    b.Property<decimal>("VarianceValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("variance_value");

                    b.Property<int?>("VerifiedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("verified_by_employee_id");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_date");

                    b.HasKey("Id");

                    b.HasIndex("CountedByEmployeeId");

                    b.HasIndex("InventoryCountId");

                    b.HasIndex("ProductBatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VerifiedByEmployeeId");

                    b.ToTable("inventory_count_items", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<string>("Variant")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variant");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.ProductBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_number");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost_per_unit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expired");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recalled");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manufacturing_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RecallReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recall_reason");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_batches", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ManagerApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OriginalSaleId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalRefundAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("OriginalSaleId");

                    b.HasIndex("ProcessedByEmployeeId");

                    b.ToTable("returns", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.ReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("OriginalSaleItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RestockedToInventory")
                        .HasColumnType("boolean");

                    b.Property<int>("ReturnId")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSaleItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_items", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("DiscountReason")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductBarcode")
                        .HasColumnType("text");

                    b.Property<int?>("ProductBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductBatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_items", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("adjusted_by_employee_id");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjustment_date");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adjustment_type");

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_employee_id");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_date");

                    b.Property<decimal>("CostImpact")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost_impact");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_after");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_before");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_change");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_number");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedByEmployeeId");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("ProductId");

                    b.ToTable("stock_adjustments", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDefectiveItemReturns")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoLogoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("AvailablePaymentMethods")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessLogoPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CurrencySymbolBefore")
                        .HasColumnType("boolean");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultPaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultReceiptEmail")
                        .HasColumnType("text");

                    b.Property<bool>("EmailReceiptEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableReturns")
                        .HasColumnType("boolean");

                    b.Property<double>("FontScaling")
                        .HasColumnType("double precision");

                    b.Property<bool>("IncludeTaxBreakdown")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PrintProductImages")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrintReceiptAutomatically")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiptCopies")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptFontSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptFooterText")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptHeaderText")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptPaperSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptTemplateLayout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequireManagerApprovalForDiscount")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireManagerApprovalForReturns")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireReceiptForReturns")
                        .HasColumnType("boolean");

                    b.Property<bool>("RestockReturnedItems")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ReturnManagerApprovalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ReturnReasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReturnTimeLimitDays")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowReceiptBarcode")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowReceiptPreview")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoundEffectsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StoreLocation")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("productCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.TaxSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableSecondaryTax")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTax")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTaxExemptions")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryTaxName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SecondaryTaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("tax_settings", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_activities", (string)null);
                });

            modelBuilder.Entity("BMS_POS_API.Models.InventoryCount", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "CompletedByEmployee")
                        .WithMany()
                        .HasForeignKey("CompletedByEmployeeId");

                    b.HasOne("BMS_POS_API.Models.Employee", "StartedByEmployee")
                        .WithMany()
                        .HasForeignKey("StartedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByEmployee");

                    b.Navigation("StartedByEmployee");
                });

            modelBuilder.Entity("BMS_POS_API.Models.InventoryCountItem", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "CountedByEmployee")
                        .WithMany()
                        .HasForeignKey("CountedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.InventoryCount", "InventoryCount")
                        .WithMany("CountItems")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatchId");

                    b.HasOne("BMS_POS_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Employee", "VerifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("VerifiedByEmployeeId");

                    b.Navigation("CountedByEmployee");

                    b.Navigation("InventoryCount");

                    b.Navigation("Product");

                    b.Navigation("ProductBatch");

                    b.Navigation("VerifiedByEmployee");
                });

            modelBuilder.Entity("BMS_POS_API.Models.ProductBatch", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BMS_POS_API.Models.Return", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId");

                    b.HasOne("BMS_POS_API.Models.Sale", "OriginalSale")
                        .WithMany()
                        .HasForeignKey("OriginalSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Employee", "ProcessedByEmployee")
                        .WithMany()
                        .HasForeignKey("ProcessedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("OriginalSale");

                    b.Navigation("ProcessedByEmployee");
                });

            modelBuilder.Entity("BMS_POS_API.Models.ReturnItem", b =>
                {
                    b.HasOne("BMS_POS_API.Models.SaleItem", "OriginalSaleItem")
                        .WithMany()
                        .HasForeignKey("OriginalSaleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Return", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalSaleItem");

                    b.Navigation("Product");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("BMS_POS_API.Models.Sale", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BMS_POS_API.Models.SaleItem", b =>
                {
                    b.HasOne("BMS_POS_API.Models.ProductBatch", null)
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductBatchId");

                    b.HasOne("BMS_POS_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BMS_POS_API.Models.StockAdjustment", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "AdjustedByEmployee")
                        .WithMany()
                        .HasForeignKey("AdjustedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS_POS_API.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId");

                    b.HasOne("BMS_POS_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdjustedByEmployee");

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BMS_POS_API.Models.UserActivity", b =>
                {
                    b.HasOne("BMS_POS_API.Models.Employee", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BMS_POS_API.Models.InventoryCount", b =>
                {
                    b.Navigation("CountItems");
                });

            modelBuilder.Entity("BMS_POS_API.Models.ProductBatch", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("BMS_POS_API.Models.Return", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("BMS_POS_API.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
